### ISSUE TITLE
Adm-Zip Problem

### ISSUE THREAD

**Issue by ioSphinx** [AirOne01/thetestbot#1]
Seems like adm-zip cannot extract any plugins ? or you forgot to provide a plugins folder in you repo?

**Comment by ioSphinx** [comment]
> 

Simply, it's supposed to import files from the dir that is called "plugins" which had the plugin that bypass the captcha, unfortunately i can't do anything as i don't know which folders or files were supposed to be imported . I Can understand how this code works but it would be appreciated if you could search for the "plugins" folder

**Comment by AirOne01** [comment]
Now I remember.
It used to import a specific plugin provided by a paid captcha solving service, and it imported it in the JS of the browser.
Not sure if any of that is really legal tho, so I stopped here.
You can try other ways to solve captchas.

**Comment by ioSphinx** [comment]
Yes After searching i found that paid captcha but after reading some of your code i found it uncomplete and yes making a selfbot live stream is against discord api and using a captcha solver by a bot is probably illegal because i'm pretty sure using that would break the website protection which could be like ddos without ddosing but anyways thank you for answering my questions !
